package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class GarageGUIController {
	@FXML
	private Button MenuButton;
	@FXML
	private Button SigninButton;
	@FXML
	private Label HiText;
	@FXML
	private Button HomeButton;

	// Event Listener on Button[#MenuButton].onAction
	@FXML
	public void MenuButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#HomeButton].onAction
	@FXML
	public void HomeButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
