package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;
import java.util.List;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;
import javafx.stage.Window;

public class MenuGUIController {
	@FXML
	private Button GarageButton;
	@FXML
	private Button AccountButton;
	@FXML
	private Button SignOutButton;
	@FXML
	private Button CloseMenuButton;
	@FXML
	private Label HiText;
	
    private String loggedInUsername;

    public void setLoggedInUsername(String username) {
        this.loggedInUsername = username;
        HiText.setText("Hi, " + loggedInUsername);
    }
    
    public void openMenuGUI() {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("MenuGUI.fxml"));
            Parent root = loader.load();
            Stage stage = new Stage();
            stage.setTitle("MenuGUI"); // Set the title of the MenuGUI window
            stage.setScene(new Scene(root));
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

	// Event Listener on Button[#GarageButton].onAction
	@FXML
	public void GarageButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
    public void AccountButtonClick(ActionEvent event) {
        // Close other stages
        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        Stage mainStage = getMainStage(currentStage);
        currentStage.close();

        if (mainStage != null) {
            mainStage.close();
        }

        // Open AccountInfoGUI
        FXMLLoader loader = new FXMLLoader(getClass().getResource("AccountInfoGUI.fxml"));
        Parent root;
        try {
            root = loader.load();
            AccountInfoGUIController accountInfoGUIController = loader.getController();
            accountInfoGUIController.setLoggedInUsername(loggedInUsername);
            Stage stage = new Stage();
            stage.setScene(new Scene(root, 1366, 768));
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private Stage getMainStage(Stage currentStage) {
        List<Window> windows = Stage.getWindows();
        for (Window window : windows) {
            if (window instanceof Stage && window != currentStage) {
                String title = ((Stage) window).getTitle();
                if (title != null && title.equals("Alfie Car Dealership")) {
                    return (Stage) window;
                }
            }
        }
        return null;
    }
	// Event Listener on Button[#SignOutButton].onAction
	@FXML
	public void SignOutButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#CloseMenuButton].onAction
	@FXML
	public void CloseMenuButtonClick(ActionEvent event) {
		// TODO Autogenerated
        // Get the source button
        Button button = (Button) event.getSource();
        
        // Get the stage of the button
        Stage stage = (Stage) button.getScene().getWindow();
        
        // Close the stage (window)
        stage.close();
	}
}
