package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;

public class MenuGUIController {
	@FXML
	private Button GarageButton;
	@FXML
	private Button AccountButton;
	@FXML
	private Button SignOutButton;
	@FXML
	private Button CloseMenuButton;
	@FXML
	private Label HiText;
	
    private String loggedInUsername;

    public void setLoggedInUsername(String username) {
        this.loggedInUsername = username;
        HiText.setText("Hi, " + loggedInUsername);
    }

	// Event Listener on Button[#GarageButton].onAction
	@FXML
	public void GarageButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AccountButton].onAction
	@FXML
	public void AccountButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#SignOutButton].onAction
	@FXML
	public void SignOutButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#CloseMenuButton].onAction
	@FXML
	public void CloseMenuButtonClick(ActionEvent event) {
		// TODO Autogenerated
        // Get the source button
        Button button = (Button) event.getSource();
        
        // Get the stage of the button
        Stage stage = (Stage) button.getScene().getWindow();
        
        // Close the stage (window)
        stage.close();
	}
}
