package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

import javafx.scene.control.CheckBox;

public class RegisterGUIController {
	@FXML
	private TextField UserTF;
	@FXML
	private PasswordField PasswordTF;
	@FXML
	private CheckBox showpass;
	@FXML
	private Button AlrAcc;
	@FXML
	private Button RegisterButton;
	@FXML
	private TextField EmailTF;

	// Event Listener on CheckBox[#showpass].onAction
	@FXML
	public void ShowPassCheck(ActionEvent event) {
	    if (showpass.isSelected()) {
	        PasswordTF.setPromptText(PasswordTF.getText());
	        PasswordTF.setText("");
	        PasswordTF.setDisable(true);
	    } else {
	        PasswordTF.setPromptText("");
	        PasswordTF.setDisable(false);
	    }
	}
	// Event Listener on Button[#AlrAcc].onAction
	@FXML
	public void AlrAccClick(ActionEvent event) throws IOException {
	    Parent loginRoot = FXMLLoader.load(getClass().getResource("LoginGUI.fxml"));
	    Scene loginScene = new Scene(loginRoot);
	    Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	    stage.setScene(loginScene);
	    stage.show();
	}
	// Event Listener on Button[#RegisterButton].onAction
	@FXML
	public void RegisterButtonClick(ActionEvent event) {
		// TODO Autogenerated
		
	}
}
